### ISSUE TITLE
[REQUEST] Show the music rate

### ISSUE THREAD

**Issue by KeziahMoselle** [osu-player/osuplayer#105]
**Is your feature request related to a problem? Please describe.**

Changing the music rate is hard. I don't know what the value is, and I can't easily reset it to 1x if I want
![image](https://user-images.githubusercontent.com/9168097/186880096-3d94cb3c-1512-4474-a73e-0e1e2d9a36c9.png)

**Describe the solution you'd like**

Either show the rate like so:
![image](https://user-images.githubusercontent.com/9168097/186880201-41332c42-9395-4c7d-890f-2e6eb223f24d.png)

Or maybe put some predefined points like YouTube is doing
![image](https://user-images.githubusercontent.com/9168097/186880302-0b5c446f-c520-4b32-a796-17c3a3614a6f.png)

**Comment by Founntain** [comment]
You can reset the playback speed to 1.0 by **left-clicking** the Icon next to the slider.

If you really want a tooltip that shows the current rate, we can do that for sure, but if you are fine, with the generel ability to just reset it, then I would just close this issue.

https://user-images.githubusercontent.com/28785685/186946746-c0e230db-e956-40e4-8c44-1f1d44f9411e.mp4

**Comment by KeziahMoselle** [comment]
Ha I didn't see it, thanks.

I still think it would be great to think "like an osu player" so like putting DT on and off makes more sense to me than a slider. Just my thoughts

**Comment by Founntain** [comment]
> Ha I didn't see it, thanks.
> 
> I still think it would be great to think "like an osu player" so like putting DT on and off makes more sense to me than a slider. Just my thoughts

The reason why we do it with a slider is, that are a lot of people *(including myself)* that like to increase / decrease it slightly or just a bit and not full Day -/ Nightcore.

I'll close the issue for now, if you think that we should do something more (implementation wise), then don't hessitate to re-open the issue.
