### ISSUE TITLE
[REQUEST] Discord Rich Presence

### ISSUE THREAD

**Issue by KeziahMoselle** [osu-player/osuplayer#107]
![image](https://user-images.githubusercontent.com/9168097/187071844-6aa7820b-fecb-417a-9f8d-a96130ccba97.png)

Not really an important request but could be nice to have a toggle to use Rich Presence.

**Comment by Founntain** [comment]
We had this in the old player, but now you have to use the Discord Game SDK to achieve this. We tried it back then but it made more trouble than good. However, I'll probably will look into that once again in the future.
