### ISSUE TITLE
[BUG] Importing songs with client.realm crashes the app

### ISSUE THREAD

**Issue by JuanAntonioFont** [osu-player/osuplayer#115]
**Describe the bug**
When selecting the client.realm file in setting to import the songs the app crashes. When reopening, it says "loading songs... please wait" but after an hour it didn't load anything.

**To Reproduce**
1. Go to settings
2. Click on "import osu! songs"
3. Select the client.realm file and open it
4. The app crashes

**Expected behavior**
Load osu(lazer) songs to the music player.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
 - Lazer version: 2022.911.0

**Additional context**
I have both stable and lazer versions and opening the osu!.db file works fine.

[20220921_151923.txt](https://github.com/osu-player/osuplayer/files/9618038/20220921_151923.txt)

**Comment by Founntain** [comment]
We'll look into that, this is most likely a problem because lazer is in constant development and changes it realm shema version etc.

We'll update it ASAP @Cesan is already looking at that. So expect a fix soon (the next day(s))
