### ISSUE TITLE
Addition of sorting playlists via title, artist, date added, etc. 

### ISSUE THREAD

**Issue by sajidbhuiya** [osu-player/osuplayer#94]
Within the settings menu, there is an option where you are already allowed to sort all your songs you have in your osu! songs folder via artist, title, and beatmap set ID. This sorting however is not applied in playlists, where it is sorted by date added to your collection/playlist. While this is the standard for playlists (as far as I can tell), having the flexibility to sort your playlist by artist, title, date added, and more will make finding a specific song within a playlist easier, especially to users that have imported playlists from osu! collections.

**Comment by Founntain** [comment]
Closing this because, we agreed to use the solution of #95
