### ISSUE TITLE
Search bar for playlists

### ISSUE THREAD

**Issue by sajidbhuiya** [osu-player/osuplayer#95]
As stated above, having a search bar could allow you to search for a song within a playlist, which could allow the user to play a song within their playlist while also enabling or retaining playlist mode. 

(Sorry for the idea spam xd, ideas just came after another)

**Comment by Cesan** [comment]
If we go for this one, I think also adding #94 is redundant and adds a lot of overhead to the player. The easiest solution is a search bar, so let's go for this if it's ok with you.

**Comment by Founntain** [comment]
I approve this solution more, because as @Cesan mentioned it will give to much overhead and a search bar makes more sense. Both would be redundant!

**Comment by sajidbhuiya** [comment]
Yeah after looking at it again, this would make a lot more sense due to the redundancy of both solutions if both were added. I'd go for the search bar.
